<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ["provider_id" => 1, "name" => "AFGHANISTAN", "code" => "AFG"],
            ["provider_id" => 1, "name" => "ALAND ISLANDS", "code" => "ALA"],
            ["provider_id" => 1, "name" => "ALBANIA", "code" => "ALB"],
            ["provider_id" => 1, "name" => "ALGERIA", "code" => "DZA"],
            ["provider_id" => 1, "name" => "AMERICAN SAMOA", "code" => "ASM"],
            ["provider_id" => 1, "name" => "ANDORRA", "code" => "AND"],
            ["provider_id" => 1, "name" => "ANGOLA", "code" => "AGO"],
            ["provider_id" => 1, "name" => "ANGUILLA", "code" => "AIA"],
            ["provider_id" => 1, "name" => "ANTARCTICA", "code" => "ATA"],
            ["provider_id" => 1, "name" => "ANTIGUA AND BARBUDA", "code" => "ATG"],
            ["provider_id" => 1, "name" => "ARGENTINA", "code" => "ARG"],
            ["provider_id" => 1, "name" => "ARMENIA", "code" => "ARM"],
            ["provider_id" => 1, "name" => "ARUBA", "code" => "ABW"],
            ["provider_id" => 1, "name" => "AUSTRALIA", "code" => "AUS"],
            ["provider_id" => 1, "name" => "AUSTRIA", "code" => "AUT"],
            ["provider_id" => 1, "name" => "AZERBAIJAN", "code" => "AZE"],
            ["provider_id" => 1, "name" => "BAHAMAS", "code" => "BHS"],
            ["provider_id" => 1, "name" => "BAHRAIN", "code" => "BHR"],
            ["provider_id" => 1, "name" => "BANGLADESH", "code" => "BGD"],
            ["provider_id" => 1, "name" => "BARBADOS", "code" => "BRB"],
            ["provider_id" => 1, "name" => "BELARUS", "code" => "BLR"],
            ["provider_id" => 1, "name" => "BELGIUM", "code" => "BEL"],
            ["provider_id" => 1, "name" => "BELIZE", "code" => "BLZ"],
            ["provider_id" => 1, "name" => "BENIN", "code" => "BEN"],
            ["provider_id" => 1, "name" => "BERMUDA", "code" => "BMU"],
            ["provider_id" => 1, "name" => "BHUTAN", "code" => "BTN"],
            ["provider_id" => 1, "name" => "BOLIVIA", "code" => "BOL"],
            ["provider_id" => 1, "name" => "BONAIRE, SINT EUSTATIUS AND SABA", "code" => "BES"],
            ["provider_id" => 1, "name" => "BOSNIA AND HERZEGOVINA", "code" => "BIH"],
            ["provider_id" => 1, "name" => "BOTSWANA", "code" => "BWA"],
            ["provider_id" => 1, "name" => "BOUVET ISLAND", "code" => "BVT"],
            ["provider_id" => 1, "name" => "BRAZIL", "code" => "BRA"],
            ["provider_id" => 1, "name" => "BRITISH INDIAN OCEAN TERRITORY", "code" => "IOT"],
            ["provider_id" => 1, "name" => "BRUNEI DARUSSALAM", "code" => "BRN"],
            ["provider_id" => 1, "name" => "BULGARIA", "code" => "BGR"],
            ["provider_id" => 1, "name" => "BURKINA FASO", "code" => "BFA"],
            ["provider_id" => 1, "name" => "BURUNDI", "code" => "BDI"],
            ["provider_id" => 1, "name" => "CAMBODIA", "code" => "KHM"],
            ["provider_id" => 1, "name" => "CAMEROON", "code" => "CMR"],
            ["provider_id" => 1, "name" => "CANADA", "code" => "CAN"],
            ["provider_id" => 1, "name" => "CAPE VERDE", "code" => "CPV"],
            ["provider_id" => 1, "name" => "CAYMAN ISLANDS", "code" => "CYM"],
            ["provider_id" => 1, "name" => "CENTRAL AFRICAN REPUBLIC", "code" => "CAF"],
            ["provider_id" => 1, "name" => "CHAD", "code" => "TCD"],
            ["provider_id" => 1, "name" => "CHILE", "code" => "CHL"],
            ["provider_id" => 1, "name" => "CHINA", "code" => "CHN"],
            ["provider_id" => 1, "name" => "CHRISTMAS ISLAND", "code" => "CXR"],
            ["provider_id" => 1, "name" => "COCOS (KEELING) ISLANDS", "code" => "CCK"],
            ["provider_id" => 1, "name" => "COLOMBIA", "code" => "COL"],
            ["provider_id" => 1, "name" => "COMOROS", "code" => "COM"],
            ["provider_id" => 1, "name" => "CONGO", "code" => "COG"],
            ["provider_id" => 1, "name" => "CONGO, THE DEMOCRATIC REPUBLIC OF THE", "code" => "COD"],
            ["provider_id" => 1, "name" => "COOK ISLANDS", "code" => "COK"],
            ["provider_id" => 1, "name" => "COSTA RICA", "code" => "CRI"],
            ["provider_id" => 1, "name" => "COTE D'IVOIRE", "code" => "CIV"],
            ["provider_id" => 1, "name" => "CROATIA", "code" => "HRV"],
            ["provider_id" => 1, "name" => "CUBA", "code" => "CUB"],
            ["provider_id" => 1, "name" => "CURACAO", "code" => "CUW"],
            ["provider_id" => 1, "name" => "CYPRUS", "code" => "CYP"],
            ["provider_id" => 1, "name" => "CZECH REPUBLIC", "code" => "CZE"],
            ["provider_id" => 1, "name" => "DENMARK", "code" => "DNK"],
            ["provider_id" => 1, "name" => "DJIBOUTI", "code" => "DJI"],
            ["provider_id" => 1, "name" => "DOMINICA", "code" => "DMA"],
            ["provider_id" => 1, "name" => "DOMINICAN REPUBLIC", "code" => "DOM"],
            ["provider_id" => 1, "name" => "EAST TIMOR", "code" => "TMP"],
            ["provider_id" => 1, "name" => "ECUADOR", "code" => "ECU"],
            ["provider_id" => 1, "name" => "EGYPT", "code" => "EGY"],
            ["provider_id" => 1, "name" => "EL SALVADOR", "code" => "SLV"],
            ["provider_id" => 1, "name" => "EQUATORIAL GUINEA", "code" => "GNQ"],
            ["provider_id" => 1, "name" => "ERITREA", "code" => "ERI"],
            ["provider_id" => 1, "name" => "ESTONIA", "code" => "EST"],
            ["provider_id" => 1, "name" => "ETHIOPIA", "code" => "ETH"],
            ["provider_id" => 1, "name" => "EUROPE ", "code" => "ULL"],
            ["provider_id" => 1, "name" => "FALKLAND ISLANDS (MALVINAS)", "code" => "FLK"],
            ["provider_id" => 1, "name" => "FAROE ISLANDS", "code" => "FRO"],
            ["provider_id" => 1, "name" => "FIJI", "code" => "FJI"],
            ["provider_id" => 1, "name" => "FINLAND", "code" => "FIN"],
            ["provider_id" => 1, "name" => "FRANCE", "code" => "FRA"],
            ["provider_id" => 1, "name" => "FRENCH GUIANA", "code" => "GUF"],
            ["provider_id" => 1, "name" => "FRENCH POLYNESIA", "code" => "PYF"],
            ["provider_id" => 1, "name" => "FRENCH SOUTHERN TERRITORIES", "code" => "ATF"],
            ["provider_id" => 1, "name" => "GABON", "code" => "GAB"],
            ["provider_id" => 1, "name" => "GAMBIA", "code" => "GMB"],
            ["provider_id" => 1, "name" => "GEORGIA", "code" => "GEO"],
            ["provider_id" => 1, "name" => "GERMANY", "code" => "DEU"],
            ["provider_id" => 1, "name" => "GHANA", "code" => "GHA"],
            ["provider_id" => 1, "name" => "GIBRALTAR", "code" => "GIB"],
            ["provider_id" => 1, "name" => "GREECE", "code" => "GRC"],
            ["provider_id" => 1, "name" => "GREENLAND", "code" => "GRL"],
            ["provider_id" => 1, "name" => "GRENADA", "code" => "GRD"],
            ["provider_id" => 1, "name" => "GUADELOUPE", "code" => "GLP"],
            ["provider_id" => 1, "name" => "GUAM", "code" => "GUM"],
            ["provider_id" => 1, "name" => "GUATEMALA", "code" => "GTM"],
            ["provider_id" => 1, "name" => "GUERNSEY", "code" => "GGY"],
            ["provider_id" => 1, "name" => "GUINEA", "code" => "GIN"],
            ["provider_id" => 1, "name" => "GUINEA-BISSAU", "code" => "GNB"],
            ["provider_id" => 1, "name" => "GUYANA", "code" => "GUY"],
            ["provider_id" => 1, "name" => "HAITI", "code" => "HTI"],
            ["provider_id" => 1, "name" => "HEARD AND MCDONALD ISLANDS", "code" => "HMD"],
            ["provider_id" => 1, "name" => "HOLY SEE (VATICAN CITY STATE)", "code" => "VAT"],
            ["provider_id" => 1, "name" => "HONDURAS", "code" => "HND"],
            ["provider_id" => 1, "name" => "HONG KONG", "code" => "HKG"],
            ["provider_id" => 1, "name" => "HUNGARY", "code" => "HUN"],
            ["provider_id" => 1, "name" => "ICELAND", "code" => "ISL"],
            ["provider_id" => 1, "name" => "INDIA", "code" => "IND"],
            ["provider_id" => 1, "name" => "INDONESIA", "code" => "IDN"],
            ["provider_id" => 1, "name" => "IRAN (ISLAMIC REPUBLIC OF)", "code" => "IRN"],
            ["provider_id" => 1, "name" => "IRAQ", "code" => "IRQ"],
            ["provider_id" => 1, "name" => "IRELAND", "code" => "IRL"],
            ["provider_id" => 1, "name" => "ISLE OF MAN", "code" => "IMN"],
            ["provider_id" => 1, "name" => "ISRAEL", "code" => "ISR"],
            ["provider_id" => 1, "name" => "ITALY", "code" => "ITA"],
            ["provider_id" => 1, "name" => "JAMAICA", "code" => "JAM"],
            ["provider_id" => 1, "name" => "JAPAN", "code" => "JPN"],
            ["provider_id" => 1, "name" => "JERSEY", "code" => "JEY"],
            ["provider_id" => 1, "name" => "JORDAN", "code" => "JOR"],
            ["provider_id" => 1, "name" => "KAZAKHSTAN", "code" => "KAZ"],
            ["provider_id" => 1, "name" => "KENYA", "code" => "KEN"],
            ["provider_id" => 1, "name" => "KIRIBATI", "code" => "KIR"],
            ["provider_id" => 1, "name" => "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "code" => "PRK"],
            ["provider_id" => 1, "name" => "KOREA, REPUBLIC OF", "code" => "KOR"],
            ["provider_id" => 1, "name" => "KOSOVO", "code" => "KOS"],
            ["provider_id" => 1, "name" => "KUWAIT", "code" => "KWT"],
            ["provider_id" => 1, "name" => "KYRGYZSTAN", "code" => "KGZ"],
            ["provider_id" => 1, "name" => "LAO PEOPLE'S DEMOCRATIC REPUBLIC", "code" => "LAO"],
            ["provider_id" => 1, "name" => "LATIN AMERICA ", "code" => "ULL"],
            ["provider_id" => 1, "name" => "LATVIA", "code" => "LVA"],
            ["provider_id" => 1, "name" => "LEBANON", "code" => "LBN"],
            ["provider_id" => 1, "name" => "LESOTHO", "code" => "LSO"],
            ["provider_id" => 1, "name" => "LIBERIA", "code" => "LBR"],
            ["provider_id" => 1, "name" => "LIBYAN ARAB JAMAHIRIYA", "code" => "LBY"],
            ["provider_id" => 1, "name" => "LIECHTENSTEIN", "code" => "LIE"],
            ["provider_id" => 1, "name" => "LITHUANIA", "code" => "LTU"],
            ["provider_id" => 1, "name" => "LUXEMBOURG", "code" => "LUX"],
            ["provider_id" => 1, "name" => "MACAU", "code" => "MAC"],
            ["provider_id" => 1, "name" => "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "code" => "MKD"],
            ["provider_id" => 1, "name" => "MADAGASCAR", "code" => "MDG"],
            ["provider_id" => 1, "name" => "MALAWI", "code" => "MWI"],
            ["provider_id" => 1, "name" => "MALAYSIA", "code" => "MYS"],
            ["provider_id" => 1, "name" => "MALDIVES", "code" => "MDV"],
            ["provider_id" => 1, "name" => "MALI", "code" => "MLI"],
            ["provider_id" => 1, "name" => "MALTA", "code" => "MLT"],
            ["provider_id" => 1, "name" => "MARSHALL ISLANDS", "code" => "MHL"],
            ["provider_id" => 1, "name" => "MARTINIQUE", "code" => "MTQ"],
            ["provider_id" => 1, "name" => "MAURITANIA", "code" => "MRT"],
            ["provider_id" => 1, "name" => "MAURITIUS", "code" => "MUS"],
            ["provider_id" => 1, "name" => "MAYOTTE", "code" => "MYT"],
            ["provider_id" => 1, "name" => "MEXICO", "code" => "MEX"],
            ["provider_id" => 1, "name" => "MICRONESIA, FEDERATED STATES OF", "code" => "FSM"],
            ["provider_id" => 1, "name" => "MOLDOVA, REPUBLIC OF", "code" => "MDA"],
            ["provider_id" => 1, "name" => "MONACO", "code" => "MCO"],
            ["provider_id" => 1, "name" => "MONGOLIA", "code" => "MNG"],
            ["provider_id" => 1, "name" => "MONTENEGRO", "code" => "MNE"],
            ["provider_id" => 1, "name" => "MONTSERRAT", "code" => "MSR"],
            ["provider_id" => 1, "name" => "MOROCCO", "code" => "MAR"],
            ["provider_id" => 1, "name" => "MOZAMBIQUE", "code" => "MOZ"],
            ["provider_id" => 1, "name" => "MYANMAR", "code" => "MMR"],
            ["provider_id" => 1, "name" => "NAMIBIA", "code" => "NAM"],
            ["provider_id" => 1, "name" => "NAURU", "code" => "NRU"],
            ["provider_id" => 1, "name" => "NEPAL", "code" => "NPL"],
            ["provider_id" => 1, "name" => "NETHERLANDS, THE", "code" => "NLD"],
            ["provider_id" => 1, "name" => "NEW CALEDONIA", "code" => "NCL"],
            ["provider_id" => 1, "name" => "NEW ZEALAND", "code" => "NZL"],
            ["provider_id" => 1, "name" => "NICARAGUA", "code" => "NIC"],
            ["provider_id" => 1, "name" => "NIGER", "code" => "NER"],
            ["provider_id" => 1, "name" => "NIGERIA", "code" => "NGA"],
            ["provider_id" => 1, "name" => "NIUE", "code" => "NIU"],
            ["provider_id" => 1, "name" => "NORFOLK ISLAND", "code" => "NFK"],
            ["provider_id" => 1, "name" => "NORTHERN MARIANA ISLANDS", "code" => "MNP"],
            ["provider_id" => 1, "name" => "NORWAY", "code" => "NOR"],
            ["provider_id" => 1, "name" => "OMAN", "code" => "OMN"],
            ["provider_id" => 1, "name" => "PAKISTAN", "code" => "PAK"],
            ["provider_id" => 1, "name" => "PALAU", "code" => "PLW"],
            ["provider_id" => 1, "name" => "PALESTINE", "code" => "PSE"],
            ["provider_id" => 1, "name" => "PANAMA", "code" => "PAN"],
            ["provider_id" => 1, "name" => "PAPUA NEW GUINEA", "code" => "PNG"],
            ["provider_id" => 1, "name" => "PARAGUAY", "code" => "PRY"],
            ["provider_id" => 1, "name" => "PERU", "code" => "PER"],
            ["provider_id" => 1, "name" => "PHILIPPINES", "code" => "PHL"],
            ["provider_id" => 1, "name" => "PITCAIRN", "code" => "PCN"],
            ["provider_id" => 1, "name" => "POLAND", "code" => "POL"],
            ["provider_id" => 1, "name" => "PORTUGAL", "code" => "PRT"],
            ["provider_id" => 1, "name" => "PUERTO RICO", "code" => "PRI"],
            ["provider_id" => 1, "name" => "QATAR", "code" => "QAT"],
            ["provider_id" => 1, "name" => "REUNION", "code" => "REU"],
            ["provider_id" => 1, "name" => "ROMANIA", "code" => "ROU"],
            ["provider_id" => 1, "name" => "RUSSIA", "code" => "RUS"],
            ["provider_id" => 1, "name" => "RWANDA", "code" => "RWA"],
            ["provider_id" => 1, "name" => "SAINT BARTHÉLEMY", "code" => "BLM"],
            ["provider_id" => 1, "name" => "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA", "code" => "SHN"],
            ["provider_id" => 1, "name" => "SAINT KITTS AND NEVIS", "code" => "KNA"],
            ["provider_id" => 1, "name" => "SAINT LUCIA", "code" => "LCA"],
            ["provider_id" => 1, "name" => "SAINT MARTIN", "code" => "MAF"],
            ["provider_id" => 1, "name" => "SAINT VINCENT AND THE GRENADINES", "code" => "VCT"],
            ["provider_id" => 1, "name" => "SAMOA", "code" => "WSM"],
            ["provider_id" => 1, "name" => "SAN MARINO", "code" => "SMR"],
            ["provider_id" => 1, "name" => "SAO TOME AND PRÍNCIPE", "code" => "STP"],
            ["provider_id" => 1, "name" => "SAUDI ARABIA", "code" => "SAU"],
            ["provider_id" => 1, "name" => "SENEGAL", "code" => "SEN"],
            ["provider_id" => 1, "name" => "SERBIA", "code" => "SRB"],
            ["provider_id" => 1, "name" => "SEYCHELLES", "code" => "SYC"],
            ["provider_id" => 1, "name" => "SIERRA LEONE", "code" => "SLE"],
            ["provider_id" => 1, "name" => "SINGAPORE", "code" => "SGP"],
            ["provider_id" => 1, "name" => "SINT MAARTEN (DUTCH PART)", "code" => "SXM"],
            ["provider_id" => 1, "name" => "SLOVAKIA", "code" => "SVK"],
            ["provider_id" => 1, "name" => "SLOVENIA", "code" => "SVN"],
            ["provider_id" => 1, "name" => "SOLOMON ISLANDS", "code" => "SLB"],
            ["provider_id" => 1, "name" => "SOMALIA", "code" => "SOM"],
            ["provider_id" => 1, "name" => "SOUTH AFRICA", "code" => "ZAF"],
            ["provider_id" => 1, "name" => "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "code" => "SGS"],
            ["provider_id" => 1, "name" => "SOUTH SUDAN", "code" => "SSD"],
            ["provider_id" => 1, "name" => "SPAIN", "code" => "ESP"],
            ["provider_id" => 1, "name" => "SRI LANKA", "code" => "LKA"],
            ["provider_id" => 1, "name" => "ST. PIERRE AND MIQUELON", "code" => "SPM"],
            ["provider_id" => 1, "name" => "SUDAN", "code" => "SDN"],
            ["provider_id" => 1, "name" => "SURINAME", "code" => "SUR"],
            ["provider_id" => 1, "name" => "SVALBARD AND JAN MAYEN ISLANDS", "code" => "SJM"],
            ["provider_id" => 1, "name" => "SWAZILAND", "code" => "SWZ"],
            ["provider_id" => 1, "name" => "SWEDEN", "code" => "SWE"],
            ["provider_id" => 1, "name" => "SWITZERLAND", "code" => "CHE"],
            ["provider_id" => 1, "name" => "SYRIAN ARAB REPUBLIC", "code" => "SYR"],
            ["provider_id" => 1, "name" => "TAIWAN", "code" => "TWN"],
            ["provider_id" => 1, "name" => "TAJIKISTAN", "code" => "TJK"],
            ["provider_id" => 1, "name" => "TANZANIA, UNITED REPUBLIC OF", "code" => "TZA"],
            ["provider_id" => 1, "name" => "THAILAND", "code" => "THA"],
            ["provider_id" => 1, "name" => "TIMOR-LESTE", "code" => "TLS"],
            ["provider_id" => 1, "name" => "TOGO", "code" => "TGO"],
            ["provider_id" => 1, "name" => "TOKELAU", "code" => "TKL"],
            ["provider_id" => 1, "name" => "TONGA", "code" => "TON"],
            ["provider_id" => 1, "name" => "TRINIDAD AND TOBAGO", "code" => "TTO"],
            ["provider_id" => 1, "name" => "TUNISIA", "code" => "TUN"],
            ["provider_id" => 1, "name" => "TURKEY", "code" => "TUR"],
            ["provider_id" => 1, "name" => "TURKMENISTAN", "code" => "TKM"],
            ["provider_id" => 1, "name" => "TURKS AND CAICOS ISLANDS", "code" => "TCA"],
            ["provider_id" => 1, "name" => "TUVALU", "code" => "TUV"],
            ["provider_id" => 1, "name" => "UGANDA", "code" => "UGA"],
            ["provider_id" => 1, "name" => "UKRAINE", "code" => "UKR"],
            ["provider_id" => 1, "name" => "UNITED ARAB EMIRATES", "code" => "ARE"],
            ["provider_id" => 1, "name" => "UNITED KINGDOM", "code" => "GBR"],
            ["provider_id" => 1, "name" => "UNITED STATES MINOR OUTLYING ISLANDS", "code" => "UMI"],
            ["provider_id" => 1, "name" => "URUGUAY", "code" => "URY"],
            ["provider_id" => 1, "name" => "USA", "code" => "USA"],
            ["provider_id" => 1, "name" => "UZBEKISTAN", "code" => "UZB"],
            ["provider_id" => 1, "name" => "VANUATU", "code" => "VUT"],
            ["provider_id" => 1, "name" => "VENEZUELA", "code" => "VEN"],
            ["provider_id" => 1, "name" => "VIETNAM", "code" => "VNM"],
            ["provider_id" => 1, "name" => "VIRGIN ISLANDS (BRITISH)", "code" => "VGB"],
            ["provider_id" => 1, "name" => "VIRGIN ISLANDS (U.S.)", "code" => "VIR"],
            ["provider_id" => 1, "name" => "WALLIS AND FUTUNA ISLANDS", "code" => "WLF"],
            ["provider_id" => 1, "name" => "WESTERN SAHARA", "code" => "ESH"],
            ["provider_id" => 1, "name" => "YEMEN", "code" => "YEM"],
            ["provider_id" => 1, "name" => "YUGOSLAVIA", "code" => "YUG"],
            ["provider_id" => 1, "name" => "ZAMBIA", "code" => "ZMB"],
            ["provider_id" => 1, "name" => "ZIMBABWE", "code" => "ZWE"],
        ];

        foreach($countries as $country){
            DB::table('countries')->insert($country);
        }
    }
}
